apiVersion: loadrugby-app-test.jmeter.com/v1alpha1
kind: Jmeter
metadata:
  name: tqa
  namespace: tqa
spec:
  # Add fields here
  slave_size: 2
  jmeter_master_image: kubernautslabs/jmeter_master:larugby-app-test
  jmeter_master_service_type: LoadBalancer
  jmeter_slave_image: kubernautslabs/jmeter_slave:larugby-app-test
  grafana_server_root: /
  grafana_service_type: LoadBalancer
  grafana_image: grafana/grafana:5.2.0
  influxdb_service_type: LoadBalancer
  influxdb_image: influxdb:1.8.4
  grafana_install: "true"
  grafana_reporter_install: "false"
  grafana_reporter_image: kubernautslabs/jmeter-reporter:larugby-app-test
  influxdb_install: "true"
